# Site settings
title: Petr Vlk
header-img: img/home-bg.jpg
email: hello@imagiag.com
description: "Description, eventually"
baseurl: "/cblog"
url: "http://www.petrvlk.com"
twitter_username: imagiag
github_username:  imagiag
facebook_username:  none

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
